/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sample_First */

#ifndef _Included_sample_First
#define _Included_sample_First
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sample_First
 * Method:    findMax
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_sample_First_findMax
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
